name: build

on:
  push:

jobs:
  build:
    name: build-${{ matrix.os }}-ghc-${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        ghc:
          - 9.4.4
    steps:
      - run: sudo apt install ccache llvm ninja-build
        if: startsWith(matrix.os, 'ubuntu-')

      - run: |
          brew install ccache ninja
          pushd $(mktemp -d)
            ln -s $(brew --prefix llvm)/bin/llvm-ar
            echo $PWD >> $GITHUB_PATH
          popd
        if: startsWith(matrix.os, 'macos-')

      - uses: haskell/actions/setup@v2.3.4
        with:
          ghc-version: ${{ matrix.ghc }}

      - uses: actions/checkout@v3

      - run: git submodule update --init --depth 1

      - uses: actions/cache@v3
        with:
          path: ~/.cache/ccache
          key: 0-ccache-ubuntu-latest-${{ github.run_id }}
          restore-keys: |
            0-ccache-ubuntu-latest
        if: startsWith(matrix.os, 'ubuntu-')

      - uses: actions/cache@v3
        with:
          path: ~/Library/Caches/ccache
          key: 0-ccache-macos-latest-${{ github.run_id }}
          restore-keys: |
            0-ccache-macos-latest
        if: startsWith(matrix.os, 'macos-')

      - run: |
          pushd node
          CC="ccache cc" CXX="ccache c++" ./configure --enable-static --experimental-enable-pointer-compression --ninja
          popd
          ninja -v -C node/out/Release

      - run: ./et.mjs

      - run: |
          pushd node
          git clean -xdf
          CC="ccache cc" CXX="ccache c++" ./configure --experimental-enable-pointer-compression --ninja --shared
          popd
          ninja -v -C node/out/Release

      - run: |
          ghc --version
          cabal --version
          cp node/out/Release/lib/libnode.so.111 node/out/Release/libshoggoth.so
          echo :q | ghci -v node/out/Release/libshoggoth.so

      - run: ccache --recompress 19
